# Generated by Django 2.2.4 on 2019-08-22 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('rua', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('img_perfil', models.ImageField(blank=True, default='default/Empresa.jpg', null=True, upload_to='images/', verbose_name='Imagem')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=255, null=True, verbose_name='Estado')),
                ('atuacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Atuacao')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cpf')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('linguagens', models.TextField(blank=True, null=True, verbose_name='Linguagens')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='e-mail')),
                ('senha', models.CharField(max_length=255, verbose_name='senha')),
                ('profissao', models.CharField(blank=True, max_length=255, null=True, verbose_name='profissão')),
                ('img_perfil', models.ImageField(blank=True, default='default/User.png', null=True, upload_to='images_pessoa/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('respondida', models.BooleanField(default=False)),
                ('correta', models.BooleanField(default=False)),
                ('Framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='demo.Framework')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='demo.Area')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='demo.Disciplina')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='demo.Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Exp_pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valores', models.TextField(blank=True, null=True, verbose_name='valores')),
                ('experiencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('selecionada', models.BooleanField(default=False)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativa', to='demo.Pergunta')),
            ],
        ),
    ]
