# Generated by Django 2.2.4 on 2019-08-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alternativa_area_disciplina_framework_nivel_pergunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='experiencia',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='img_perfil',
            field=models.ImageField(blank=True, default='static/imgs/User.png', null=True, upload_to='images_pessoa/', verbose_name='Imagem'),
        ),
    ]
