# Generated by Django 2.2.4 on 2019-08-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20190821_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='img_perfil',
            field=models.ImageField(blank=True, default='default/User.png', null=True, upload_to='images_pessoa/', verbose_name='Imagem'),
        ),
    ]
